# .streamlit/secrets.toml
# Add your OpenAI API key here
OPENAI_API_KEY = "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"
